import { useState, lazy } from 'react';
import { useAppSelector } from '../../../../store/hooks';
import { useVpHistData } from '../hooks/useData/useVpHistData';
import { useVpImageQuery } from '../hooks/useQuery/useVpImageQuery';

const VpChartHighcharts = lazy(() => import('../../../../shared/components/charts/HighchartsVP'));
const BaseChartModal = lazy(() => import('../../common/BaseChartModal'));

const VpMdlHistory = () => {
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [displayMode, setDisplayMode] = useState<'png' | 'interactive'>('interactive');

    const toggleModal = () => {
        setIsModalOpen(!isModalOpen);
    }

    // Display mode handlers
    const handleDisplayImage = () => {
        setDisplayMode('png');
    }
    const handleDisplayInteractiveChart = () => {
        setDisplayMode('interactive');
    }

    // Actual user selected altitude from a global altitude slice that we plot on the interactive chart
    const { currentAltitude } = useAppSelector(state => state.hist_altitude);
    // Payload containing parameters to query the API server 
    const { vpPayload } = useAppSelector(state => state.vp_histchart);

    // Chart data fetching using React queries custom hooks enable the fetching only if the modal opens and display mode is set to 'interactive'
    const { isLoading, data, error } = useVpHistData(isModalOpen && displayMode === 'interactive');
    // Tanstack query fetching a chart image generated by the server encoded in base64, activated only if the modal opens and display mode set to 'png'
    const { data: vpImageData, isLoading: vpImageLoading, error: vpImageError } = useVpImageQuery(vpPayload, (isModalOpen && displayMode === 'png'));


    const capitalize = (s: string | undefined) => {
        if( s === undefined) return "";
        return s ? s[0].toLocaleUpperCase() + s.slice(1) : s;
    }
  return (
    <BaseChartModal
        title={`${capitalize(data?.query_spec)} - ${data?.name ?? ''} (${data?.units ?? ''})`}
        selectedHeight={currentAltitude}
        data={data}
        dataError={error}
        dataImage={vpImageData}
        dataLoading={isLoading}
        displayMode={displayMode}
        handleDisplayImage={handleDisplayImage}
        handleDisplayInteractiveChart={handleDisplayInteractiveChart}
        imageError={vpImageError}
        imageLoading={vpImageLoading}
        isModalOpen={isModalOpen}
        toggleModal={toggleModal}
        downloadFilename={`${vpPayload?.species}_${vpPayload?.parameter}-${vpPayload?.time}`}
        renderImage={(imgRef) => (
            <img ref={imgRef} src={vpImageData} alt='vp-image-history'/>
        )}
        renderInteractive={(chartRef) => (
            <div className="lg:w-1/2 w-full">
                <VpChartHighcharts
                    data={data!}
                    ref={chartRef}
                    chartHeight={500}
                    displayTitle
                />
            </div>
        )}
    />
  )
}

export default VpMdlHistory;
